name: "P6 GHA: Enqueue PR to Merge Queue (after CI)"
description: "P6 GHA: Enqueue PR to Merge Queue (after CI)"
author: "Philip M. Gollucci"

inputs:
  gh_token:
    description: "GitHub Token with repo permissions"
    required: true

runs:
  using: "composite"
  steps:
    - name: Get triggering PR number (single)
      id: pr
      if: >
        github.event.workflow_run.event == 'pull_request' &&
        github.event.workflow_run.conclusion == 'success'
      shell: bash
      run: |
        PR=$(jq -r '.workflow_run.pull_requests[0].number // empty' "$GITHUB_EVENT_PATH")
        echo "pr=$PR"
        echo "pr=$PR" >> "$GITHUB_OUTPUT"

    - name: Enqueue the single PR into default Merge Queue
      if: >
        steps.pr.outputs.pr != '' 
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
        REPO: ${{ github.repository }}
        PR: ${{ steps.pr.outputs.pr }}
      shell: bash
      run: |
        echo "Queueing PR #$PR in $REPO"
        case $REPO in
        pgollucci/) gh pr merge --merge -R "$REPO" "$PR" ;;
        *) gh pr merge -R "$REPO" "$PR" ;;
        
