name: "P6 GHA: Enqueue PR to Merge Queue (after CI)"
description: "P6 GHA: Enqueue PR to Merge Queue (after CI)"
author: "Philip M. Gollucci"

runs:
  using: "composite"
  steps:
    - name: Get triggering PR number (single)
      id: pr
      if: >
        github.event.workflow_run.event == 'pull_request' &&
        github.event.workflow_run.conclusion == 'success'
      shell: bash
      run: |
        PR=$(jq -r '.workflow_run.pull_requests[0].number // empty' "$GITHUB_EVENT_PATH")
        echo "pr=$PR" >> "$GITHUB_OUTPUT"

    - name: Enqueue the single PR into default Merge Queue
      if: steps.pr.outputs.pr != ''
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
        PR: ${{ steps.pr.outputs.pr }}
      shell: bash
      run: |
        echo "Queueing PR #$PR in $REPO"
        # No strategy flag: for branches with Merge Queue enabled,
        # this adds the PR to the queue (or enables auto-merge if checks still pending).
        gh pr merge -R "$REPO" "$PR"
