name: Enqueue PR to Merge Queue (after CI)

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  enqueue:
    runs-on: ubuntu-latest
    name: Enqueue PR to Merge Queue (after CI)
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Enqueue PR
        uses: ./
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
